#include <cmath>
#include "Temperature.h"

Temperature::Temperature(double startTemp) {
    ambientTemp = startTemp;
    oilTemp = startTemp;
    coolant = startTemp;
}

void Temperature::setAmbient(double temp) {
    ambientTemp = temp;
}
/**
 * Updates the thermal state of the engine.
 * @param rpm Engine speed in Revolutions Per Minute (e.g., 800 - 7000)
 * @param load Normalized engine load (0.0 = Idle, 1.0 = Full Throttle)
 * @param speed Speed in km/h (Used for airflow calculation)
 * @param time Time elapsed since last update in Seconds (e.g., 0.1 for 10Hz)
 */
void Temperature::update(int rpm, double load, double speed, double time) {
    // 1. ENERGY INPUT (Heat generated by combustion)
        // Load is expressed as 0.0 to 1.0 (0% to 100%)
        double heatPowerInput = (rpm * load);
        double deltaHeat = heatPowerInput * THERMAL_MASS_INVERSE;

        // 2. COOLING SYSTEM LOGIC
        if (coolant > THERMOSTAT_OPEN_TEMP) {
            waterPump = true;
        }

        // 3. ENERGY OUTPUT (Heat Dissipation)
        // Passive cooling from vehicle movement
        double coolingPower = speed * PASSIVE_AIR_COOLING;

        if (waterPump) {
            // Radiator cooling: rate is proportional to (T_engine - T_ambient)
            double ambientTemp = 20.0; 
            coolingPower += (coolant - ambientTemp) * RADIATOR_EFFICIENCY;
        }

        // 4. STATE INTEGRATION (The "Physics" Step)
        // Net change = (Heat In - Heat Out) * Time Step
        coolant += (deltaHeat - (coolingPower * THERMAL_MASS_INVERSE)) * time;
        
        // 5. SECONDARY FLUIDS (Oil follows the coolant temperature curve)
        oilTemp += (coolant - oilTemp) * OIL_COUPLING_FACTOR;
}

double Temperature::getCoolantTemp() {
    return coolant;
}

double Temperature::getOilTemp() {
    return oilTemp;
}

double Temperature::getEfficiency() {
    double coolantError = std::abs(coolant - TARGET_COOLANT_TEMP); // find deviation from ideal temp (90)
    double coolantScore = 100 - coolantError * 1.5; // 1.5% penalty per degree

    double oilError = std::abs(oilTemp - TARGET_OIL_TEMP); // deviation from 105
    double oilScore = 100 - oilError * 2; // 2% penalty per degree

    if(coolantScore < 0) {
        coolantScore = 0;
    }
                                // clamp scores
    if (oilScore < 0) {
        oilScore = 0;
    }

    return (coolantScore * COOLANT_FACTOR) + (oilScore * OIL_FACTOR); //coolant is weighted 40% and oil 60%
}