import streamlit as st
import subprocess
import pandas as pd
import os
import platform
import re

# --- PAGE CONFIG ---
st.set_page_config(page_title="RS 6 Digital Twin Simulator", layout="wide")

st.markdown("""
<style>
.stSlider, .stNumberInput, .stSelectbox { background-color: #1e1e1e !important; border-radius: 8px; padding: 10px; color: #FFFFFF; }
h1 { font-family: 'Arial', sans-serif; text-transform: uppercase; color: #FFFFFF; }
</style>
""", unsafe_allow_html=True)

def run_cpp_digital_twin(passengers, cargo, windows_open, fuel, throttle, ambient, sim_time):
    # Format the exact 7 inputs matching the C++ std::cin order
    window_char = 'Y' if windows_open else 'N'
    input_string = f"{passengers}\n{cargo}\n{window_char}\n{fuel}\n{throttle}\n{ambient}\n{sim_time}\n"
    
    # Handle Windows vs Mac/Linux executable naming
    exe_name = 'a.exe' if platform.system() == 'Windows' else './a.out'
    
    try:
        # Run the C++ program, passing the inputs via stdin
        process = subprocess.run([exe_name], input=input_string, capture_output=True, text=True)
        output = process.stdout
        
        # Regex to parse the output average scores printed by maindemo.cpp
        drag_match = re.search(r"Drag Score:\s+([0-9.]+)", output)
        temp_match = re.search(r"Temperature Score:\s+([0-9.]+)", output)
        speed_match = re.search(r"Speed Score:\s+([0-9.]+)", output)
        weight_match = re.search(r"Weight Score:\s+([0-9.]+)", output)
        
        if drag_match and temp_match and speed_match and weight_match:
            scores = {
                "drag": float(drag_match.group(1)),
                "temp": float(temp_match.group(1)),
                "speed": float(speed_match.group(1)),
                "weight": float(weight_match.group(1))
            }
            # Calculate an aggregate overall score
            scores["overall"] = sum(scores.values()) / 4.0
            return scores, output
        else:
            st.error("Could not parse scores from C++ output. Ensure the C++ script is compiled and running properly.")
            st.text("Raw Output:\n" + output)
            return None, output
            
    except FileNotFoundError:
        st.error(f"Could not find {exe_name}. Did you run the g++ compile command first?")
        return None, ""
    except Exception as e:
        st.error(f"Execution failed: {e}")
        return None, ""

# --- UI LAYOUT ---
st.title("RS 6 DIGITAL TWIN: FUEL EFFICIENCY SIMULATOR")

col_inputs, col_main = st.columns([1, 3])

with col_inputs:
    st.header("INPUTS")
    
    with st.expander("CONFIGURE SIMULATION", expanded=True):
        p_kg = st.number_input("Total Passenger Mass (kg)", min_value=0.0, max_value=1000.0, value=150.0)
        c_kg = st.number_input("Cargo Mass (kg)", min_value=0.0, max_value=1000.0, value=50.0)
        
        # Maps to Y/N character for standard input
        win_open = st.selectbox("Windows Open?", [False, True], format_func=lambda x: "Yes" if x else "No")
        
        fuel_fraction = st.slider("Fuel Level (0.0 = Empty, 1.0 = Full)", 0.0, 1.0, 0.8)
        throttle_in = st.slider("Throttle Level (0.0 = None, 1.0 = Full)", 0.0, 1.0, 1.0)
        ambient_in = st.number_input("Ambient Temperature (C)", min_value=-30.0, max_value=50.0, value=20.0)
        sim_time = st.number_input("Simulation Duration (Seconds)", min_value=10.0, max_value=600.0, value=100.0, step=10.0)
        
        run_sim = st.button("Run Digital Twin Simulation", type="primary", use_container_width=True)

with col_main:
    st.header("DIGITAL TWIN TELEMETRY INTERFACE")

    if run_sim:
        with st.spinner("Running C++ simulation engine..."):
            scores, raw_out = run_cpp_digital_twin(p_kg, c_kg, win_open, fuel_fraction, throttle_in, ambient_in, sim_time)

        if scores:
            st.subheader("AVERAGE EFFICIENCY SCORES")
            
            st.markdown(f"""
            <div style='text-align: center; padding-bottom: 20px;'>
                <p style='font-size: 60px; font-weight: bold; color: #00FF00; margin-bottom: 0px;'>
                    {scores['overall']:.1f} / 100
                </p>
                <p style='font-size: 20px; color: #AAAAAA; margin-top: 0px;'>OVERALL SCORE</p>
            </div>
            """, unsafe_allow_html=True)
            
            st.progress(int(max(0, min(100, scores['overall']))))

            c1, c2, c3, c4 = st.columns(4)
            c1.metric("Drag Score", f"{scores['drag']:.1f}")
            c2.metric("Temperature Score", f"{scores['temp']:.1f}")
            c3.metric("Speed/Accel Score", f"{scores['speed']:.1f}")
            c4.metric("Weight Score", f"{scores['weight']:.1f}")

            st.markdown("---")
            
            # Read the CSV output generated by maindemo.cpp
            if os.path.exists("carTelemetry.csv"):
                df = pd.read_csv("carTelemetry.csv")
                
                st.subheader("DYNAMIC TELEMETRY GRAPHS")
                
                g1, g2 = st.columns(2)
                
                with g1:
                    st.markdown("**RPM Over Time**")
                    st.line_chart(df, x="Time (s)", y="RPM", color="#FF5733")
                    
                with g2:
                    st.markdown("**Torque vs RPM**")
                    # Changed from scatter_chart to line_chart for connected lines
                    st.line_chart(df, x="RPM", y="Torque (Nm)", color="#33C1FF")
                
                st.markdown("**Dynamic Efficiency Metrics Over Time**")
                
                # Split into 3 separate graphs so acceleration isn't visually crushed by speed/drag scaling
                sg1, sg2, sg3 = st.columns(3)
                with sg1:
                    st.markdown("Speed (km/h)")
                    st.line_chart(df, x="Time (s)", y="Speed (km/h)", color="#FF33A1", height=200)
                with sg2:
                    st.markdown("Drag Force (N)")
                    st.line_chart(df, x="Time (s)", y="Drag (N)", color="#33FF57", height=200)
                with sg3:
                    st.markdown("Acceleration (m/s2)")
                    st.line_chart(df, x="Time (s)", y="Acceleration (m/s2)", color="#FFFF33", height=200)

                st.markdown("---")
                st.subheader("RAW CSV DATA (carTelemetry.csv)")
                st.dataframe(df, use_container_width=True, hide_index=True)
            else:
                st.warning("Telemetry CSV not found. Make sure maindemo.cpp writes to the correct directory.")
    else:
        st.info("Adjust the inputs on the left and click 'Run Digital Twin Simulation' to generate data.")